### ISSUE TITLE
generate_configs not working

### ISSUE THREAD

**Issue by mriehema** [creynders/grunt-generate-configs#14]
generate_configs is not working.

Node, npm and grunt are installed globally. Working with windows 7 in git bash.

```
$ grunt -V
grunt-cli v1.2.0
grunt v1.0.1
```

```
$ generate_configs
module.js:327
    throw err;
    ^

Error: Cannot find module 'grunt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\mriehema\AppData\Roaming\npm\node_modules\grunt-generate-configs\bin\generate_configs:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by jrutter** [comment]
Did this ever get fixed?

**Comment by Trimud** [comment]
Looks like `npm install grunt -g` fixes this issue.

Regards
